servers:
  - name: "local_db"
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres"
    sslmode: "disable"
  - name: "prod_db"
    host: "prod.example.com"
    port: 5432
    user: "postgres"
    password: "postgres"
    database: "postgres"
    sslmode: "disable"

report_dir: "./report"
